name: Build SunamoBazosCrawler

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoBazosCrawler
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoBazosCrawler/SunamoBazosCrawler.csproj

    - name: Build
      run: dotnet build SunamoBazosCrawler/SunamoBazosCrawler.csproj --configuration Release --no-restore

  test:
    name: Test SunamoBazosCrawler.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoBazosCrawler.Tests/SunamoBazosCrawler.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoBazosCrawler.Tests/SunamoBazosCrawler.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoBazosCrawler.Tests/SunamoBazosCrawler.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
